import './globals.css'
import { Footer, Header } from '@/components'
import ReduxProvider from '@/redux/provider'
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'

const MontserratFont = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'QPICK - HeadPhones',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='ru'>
			<body className={MontserratFont.className}>
				<div className='container'>
					<ReduxProvider>
						<Header />
						{children}
						<Footer />
					</ReduxProvider>
				</div>
			</body>
		</html>
	)
}
